// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY_4zJfz3NV2X3EQRnV6m5iPkJJyPjPRI',
    appId: '1:975896082403:web:3636ada8084adecd4912d6',
    messagingSenderId: '975896082403',
    projectId: 'bah--application',
    authDomain: 'bah--application.firebaseapp.com',
    storageBucket: 'bah--application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3-7pE1YuGJ1wwUkMoo7DuQyDtWqkkvA',
    appId: '1:975896082403:android:f6da7ec6c061252a4912d6',
    messagingSenderId: '975896082403',
    projectId: 'bah--application',
    storageBucket: 'bah--application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7gb6xNMy4N0B77-EGAaUYgOjbs0K85So',
    appId: '1:975896082403:ios:1037da007614c92c4912d6',
    messagingSenderId: '975896082403',
    projectId: 'bah--application',
    storageBucket: 'bah--application.appspot.com',
    iosClientId: '975896082403-mc9ptv3fsnnj0hd74k8s6bab5cd779vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7gb6xNMy4N0B77-EGAaUYgOjbs0K85So',
    appId: '1:975896082403:ios:1037da007614c92c4912d6',
    messagingSenderId: '975896082403',
    projectId: 'bah--application',
    storageBucket: 'bah--application.appspot.com',
    iosClientId: '975896082403-mc9ptv3fsnnj0hd74k8s6bab5cd779vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterui',
  );
}
